# Generated by Django 5.1.1 on 2024-09-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_buyerprofile_favorite_products_favorite_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierprofile',
            old_name='instabuy_account',
            new_name='instapay_account',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='instabuy_account',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='instapay_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instapay account'),
        ),
    ]
