# Generated by Django 5.1.1 on 2024-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_instabuy_account_supplierprofile_instapay_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supplier',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supplier', 'Supplier'), ('buyer', 'Buyer')], default='buyer', max_length=10, verbose_name='Role'),
        ),
    ]
