# Generated by Django 5.1.1 on 2024-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_buyerprofile_instapay_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='instabuy_account',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='instapay_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instapay account'),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='instapay_account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instapay account'),
        ),
    ]
