# Generated by Django 5.1.1 on 2024-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_buyerprofile_instabuy_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Phone Number'),
        ),
    ]
