# Generated by Django 5.1.1 on 2024-10-10 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_buyerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdocuments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
