# Generated by Django 5.1.1 on 2024-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, null=True, verbose_name='Specifications'),
        ),
    ]
