# Generated by Django 5.1.1 on 2024-09-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_review_comment_review_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Review Text'),
        ),
    ]
